### ISSUE TITLE
Could someone tell me how to put a photo in the left part?

### ISSUE THREAD

**Issue by w29593617** [orderedlist/minimal#50]

**Comment by RobinLu1209** [comment]
> _No description provided._

Hi, do you solve this problem?

**Comment by VukAnd** [comment]
```yml
theme: jekyll-theme-minimal
title: My super cool website
description: My super cool description
logo: https://mydomain.com/myimage.png
```
